### ISSUE TITLE
[BUG] Documentation of Scenario is not visible in Robot Framework logs

### ISSUE THREAD

**Issue by dschweie** [d-biehl/robotframework-gherkin-parser#1]
**Describe the bug**
The documentation of the scenario is not inside the log file of Robot Framework

**To Reproduce**
1. Execute the example code
2. Check report.html and log.html
3. The text "Dokumentation zum Szenario" is not available

If possible add some example source code like:
```Feature: Login

  Feature Description

  @regression
  Scenario: Usual Login
    Dokumentation zum Szenario
    Given Application Is Started
    Then Default User Is Logged In
```

**Expected behavior**
The documentation of scenario should be displayed in log files of Robot Framework.

**Screenshots/ Videos**
![image](https://github.com/d-biehl/robotframework-gherkin-parser/assets/41824954/9629cd1d-3e78-41be-ba54-cd87d8ef9456)
![image](https://github.com/d-biehl/robotframework-gherkin-parser/assets/41824954/c6640e8d-6ba0-4917-ba3b-0b9b2a7ea913)

**Desktop (please complete the following information):**
- VS Code Version 1.86.1
- RobotCode Version 0.73.3
- RobotCode GherkinParser Support v0.3.2 (pre-release)
- OS: Windows
- Python Version 3.11.1
- RobotFramework Version 7.0.0

**Comment by d-biehl** [comment]
fixed it, but I will make a new version not before next week
